// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1746134144);
user_pref("app.update.lastUpdateTime.region-update-timer", 1746134144);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1746134144);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1746134175);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1746134144);
user_pref("browser.region.update.updated", 1746134114);
user_pref("browser.search.region", "DE");
user_pref("calendar.caldav.googleResync", 1746134113);
user_pref("calendar.list.sortOrder", "36babfee-61d1-499b-8f21-26645a38ee60");
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.calendar-main-default", true);
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.calendar-main-in-composite", true);
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.disabled", true);
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.name", "Home");
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.type", "storage");
user_pref("calendar.registry.36babfee-61d1-499b-8f21-26645a38ee60.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Berlin");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.cache.lastUpdate", 1746137413);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250417120720");
user_pref("extensions.lastAppVersion", "128.9.2");
user_pref("extensions.lastPlatformVersion", "128.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/locale");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1d4f30c0-9499-4fbd-a2da-385807052718\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1746134496);
user_pref("ldap_2.servers.history.uid", "6f93d465-a338-4b4e-aa25-fe8563b1feaa");
user_pref("ldap_2.servers.pab.uid", "e283a11a-6795-4c8c-b358-25860942e163");
user_pref("mail.compose.attachment_reminder_keywords", ".doc,.pdf,.xls,.ppt,.rtf,.pps,attachment,attach,attached,attaching,enclosed,CV,cover letter,anbei,angehängt,angefügt,beigefügt,Anhang,anhang");
user_pref("mail.compose.big_attachments.threshold_kb", 20480);
user_pref("mail.compose.default_to_paragraph", false);
user_pref("mail.default_send_format", 3);
user_pref("mail.mdn.report.enabled", false);
user_pref("mail.nstmp_cleanup_completed", true);
user_pref("mail.rights.version", 1);
user_pref("mail.shell.checkDefaultClient", true);
user_pref("mail.spam.logging.enabled", true);
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.manualMarkMode", 1);
user_pref("mail.spam.markAsReadOnSpam", true);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "7a560285-6ffa-4fef-97f6-d22bff910b0");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.start_page_override.mstone", "128.9.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("messenger.options.messagesStyle.theme", "simple");
user_pref("network.cookie.cookieBehavior", 2);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1746134496);
user_pref("places.history.enabled", false);
user_pref("pref.general.disable_button.default_mail", false);
user_pref("pref.ldap.disable_button.edit_directories", false);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -11005);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1746145149);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1746145149);
user_pref("services.settings.thunderbird.search-config.last_check", 1746145149);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1746145149);
user_pref("spellchecker.dictionary", "en-US,de-DE");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1746134496);
user_pref("toolkit.startup.last_success", 1746137410);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20250417120720");
